services:
  app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /tmp:/tmp
      - ./demo.ipynb:/home/jovyan/demo.ipynb
    environment:
      - EARTHDATA_USERNAME=${EARTHDATA_USERNAME}
      - EARTHDATA_PASSWORD=${EARTHDATA_PASSWORD}
      - JUPYTER_ENABLE_LAB=yes
